<cfhttp 
	url="https://Anypath/api/web/Mylists('xyzz')/ZZZ" 
	method="get" 
	result="httpresult" 
        charset="utf-8" 
		domain="anyDomian"
	username="myUser"
	password="myPassword"
	authType="ntlm"
	>
</cfhttp>